name: vocobell

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Get commit message
        id: get-message
        run: echo "COMMIT_MSG=$(git log -1 --pretty=%B | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9._-' '-')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.VOCOBELL_SECRET_TOKEN_SECURE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/ewsmyth/vocobell:latest
            ghcr.io/ewsmyth/vocobell:${{ env.COMMIT_MSG }}
          labels: |
            org.opencontainers.image.source=https://github.com/ewsmyth/vocobell
